# @plugin ExplosionRegeneration
# @version 1.3.10
# @author foncused

# Do you want blocks to regenerate in random order?
# true -> regeneration will occur in random order
# false -> regeneration will occur from bottom to top (fixes gravel, sand, etc. better)
random: true

# Speed in ticks for block regeneration
# You can change the speed in-game with /blockregenspeed <speed>
# Recommended not to put this number over 200 since it uses a running task
speed: 2

# Delay in ticks before block regeneration
delay: 0

# Which particle effect would you like to use?
# To disable a particle effect, set to an empty string ""
particle: "VILLAGER_HAPPY"

# Which sound would you like to use?
# To disable a sound effect, set to an empty string ""
sound: "ENTITY_CHICKEN_EGG"

# Should TNT be exploded in a chain reaction, similar to how it would normally?
tnt-chaining:
  enabled: false
  max-fuse-ticks: 40

# Which blocks should NOT be regenerated?
filter:
  - "FIRE"

# In which worlds should ExplosionRegeneration NOT regenerate blocks?
blacklist:
  - ""

# Should ExplosionRegeneration honor WorldGuard's config and region flags?
# Setting this to true requires both WorldGuard and WorldEdit as dependencies
worldguard: false
