name: ExplosionRegeneration
main: me.foncused.explosionregeneration.ExplosionRegeneration
version: 1.3.7
author: foncused
api-version: 1.14
softdepend: [WorldEdit, WorldGuard]

commands:
  blockregenspeed:
    usage: /<command>
    aliases: [brs]
    description: Change block regeneration speed

permissions:
  explosionregeneration.blockregenspeed:
    default: false
