name: ExplosionRegeneration
main: me.foncused.explosionregeneration.main.ExplosionRegeneration
version: 1.3.2
author: foncused

commands:
  blockregenspeed:
    usage: /<command>
    aliases: [brs]
    description: Change block regeneration speed!
