name: ExplosionRegeneration
main: me.foncused.explosionregeneration.main.ExplosionRegeneration
version: 1.3.4
author: foncused

commands:
  blockregenspeed:
    usage: /<command>
    aliases: [brs]
    description: Change block regeneration speed!

permissions:
  explosionregeneration.blockregenspeed:
    default: false
